examples/hosted_agent/example-twitter.py, src/game_sdk/hosted_game/agent.py, src/game_sdk/hosted_game/sdk.py
1. Task Description
2. X Prompt Configuration
3. Follow Twitter Account
=> Allow deploy to accept

src/game_sdk/hosted_game/README.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected `correspodning` to `corresponding`
Please review the changes and let me know if any additional changes are needed.
=> fix: typos in documentation files

src/game_sdk/game/agent.py, src/game_sdk/game/api.py, src/game_sdk/game/api_v2.py, src/game_sdk/game/worker.py
Updates the GAME API calls used by the library to new endpoints
=> V2 GAME API

src/game_sdk/game/api_v2.py
=> Fix v2 api payload

plugins/stateofmika/examples/example_som.py, plugins/stateofmika/pyproject.toml, plugins/stateofmika/stateofmika_plugin_gamesdk/functions/router.py
plugin fixes
still requires an api_key
=> plugin fixes

plugins/conflux/README.md, plugins/conflux/conflux_plugin_gamesdk/conflux_plugin_gamesdk.py, plugins/conflux/pyproject.toml, plugins/conflux/tests/test_meme.py
The Conflux Plugin enables interaction with the Conflux blockchain network, specifically designed for meme token creation and management operations.
- Create new meme tokens with customizable name, symbol, and metadata
- With Automatic IPFS image upload and metadata management
- Retrieve list of created meme tokens
=> feat(conflux-plugin): basic feature for confi.pump

examples/game/example_twitter_reaction_module.py, plugins/twitter/test_twitter.py, plugins/twitter/twitter_plugin_gamesdk/twitter_plugin.py
for hackathon demo - to show an example implementation of a reaction module via worker
=> example - twitter reaction module

examples/game/test_worker.py, plugins/allora/README.md, src/game_sdk/game/agent.py
- Corrected `"wiht"` → `"with"` in a comment.  
- No functional changes were made.  
- `"Avilable"` → `"Available"` in the function list section.  
- `"wiht"` → `"with"` in a printed message.
=> Fix Typos in `test_worker.py`, `agent.py`, and `README.md`

examples/game/test_worker.py
=> chore: update test_worker.py

README.md
Changes made:
1. Added a title for the src introduction called Overview of the Source Code Structure.
2. Added a new section called Examples in the main Python SDK README, along with commands to run the examples instantly.
3. Updated the outdated hyperlinks accordingly.
4. Restructured the Useful Resources section for better clarity and navigation.
5. Added GAME Whitepaper and How To link to the Useful Resources section.
6. Updated the TypeScript plugin link to the correct URL - under Useful Resources
=> Update README.md with Updated Documentation Link and Code Execution Command

plugins/cdp/README.md, plugins/cdp/cdp_game_sdk/cdp_plugin.py, plugins/cdp/examples/cdp_agent.py, plugins/cdp/examples/cdp_worker.py, plugins/cdp/pyproject.toml, plugins/cdp/test_cdp.py
CDP Plugin for Virtuals 
Creates Plugin and basic examples for onchain actions with CDP
=> CDP Plugin For Virtuals

src/game_sdk/game/api.py, src/game_sdk/game/api_v2.py
First check for status code, before parsing json. This avoid json parsing error when response is not 200 with valid json, e.g. in case of errors from GAME.
=> Correcting response handling

.gitignore
Add files generated by JetBrains IDEs files to `.gitignore`
Add `./idea` to `.gitignore` to better avoid committing local JetBrains IDE configs to the repo. 
- Screenshots
| Before | After |
| --- | --- |
| <img width="958" alt="image" src="https://github.com/user-attachments/assets/8f7f90c2-9bd3-44d2-8ed7-4d9ab4997bdf" /> | <img width="958" alt="image" src="https://github.com/user-attachments/assets/26e64142-39b6-46ff-8f47-79a0b744d552" /> |
=> [Chore] Add JetBrains IDEs Files to .gitignore

src/game_sdk/game/agent.py, src/game_sdk/game/worker.py
=> Switch to 70B as a default model.

plugins/acp/acp_plugin_gamesdk/acp_client.py, plugins/acp/acp_plugin_gamesdk/acp_token.py, plugins/acp/tools/test_sign_memo.py
=> [WIP] Feat/sign memo api

plugins/acp/acp_plugin_gamesdk/acp_token.py
=> remove unuse code

plugins/acp/acp_plugin_gamesdk/acp_client.py, plugins/acp/acp_plugin_gamesdk/acp_token.py
=> fix search agent query not correct and rename fn name

plugins/acp/acp_plugin_gamesdk/acp_client.py, plugins/acp/acp_plugin_gamesdk/acp_plugin.py, plugins/acp/acp_plugin_gamesdk/acp_token.py, plugins/acp/examples/test_buyer.py, plugins/acp/examples/test_seller.py, plugins/acp/tools/test_sign_memo.py
=> acp to accept acp base url

plugins/acp/acp_plugin_gamesdk/acp_client.py, plugins/acp/acp_plugin_gamesdk/acp_plugin.py, plugins/acp/acp_plugin_gamesdk/interface.py
=> Fix offering missing

plugins/acp/acp_plugin_gamesdk/acp_client.py
Instead of passing in the wallet address into the function as a param. Now it just automatically gets it from the property instead.
- None
- To simplify reest_state function, and ensure a acp_client class can only reset their own state and not other agent states
- Nothing
- Nothing
- Readability and maintainability
- No
Test script:
```python
tariff_buyer_acp_token = AcpToken(
wallet_private_key=SELF_WALLET_PRIVATE_KEY,
agent_wallet_address=TARIFF_BUYER_WALLET_ADDRESS,
network_url="https://base-sepolia-rpc.publicnode.com/", …
```
=> Removed wallet address param from reset_state function

plugins/acp/acp_plugin_gamesdk/acp_plugin.py
Refactors all dictionaries into Argument objects
None
To prevent future typing errors in relation to Agent Functions
Nothing
Nothing
Readability and maintainability
No
Tested on test_buyer.py:
Working normally
=> Refactor - Converting dicts to Arguments

plugins/acp/acp_plugin_gamesdk/acp_client.py, plugins/acp/acp_plugin_gamesdk/acp_plugin.py, plugins/acp/acp_plugin_gamesdk/interface.py, plugins/acp/examples/test_buyer_reactive.py, plugins/acp/examples/test_seller_reactive.py, plugins/acp/tools/delete_completed_job.py
=> implement delete completed job

plugins/acp/pyproject.toml, plugins/acp/tools/delete_completed_job.py
- helper tool to delete all except n most recently updated completed jobs
- allow user to select which deletion method to use via main method
=> [ACP] Prune all except n jobs

plugins/twitter/examples/.env.example, plugins/twitter/twitter_plugin_gamesdk/twitter_plugin.py
Adds an authentication gate during initialization of the `TwitterPlugin` to ensure valid credentials are provided before proceeding.
- Adds a logging setup in the `TwitterPlugin` to provide authentication-related logs.
- Introduces an authentication check during initialization by calling the `_check_authentication()` method, which validates the credentials and logs the authentication status.
Tested locally. Refer to #153.
=> [Twitter Plugin] Improve Error Log

plugins/acp/examples/agentic/test_buyer.py, plugins/acp/examples/agentic/test_seller.py, plugins/acp/examples/reactive/test_buyer.py, plugins/acp/examples/reactive/test_seller.py
Fixes agent state retrieval bug
None
Nothing
Nothing
Stability of program
No
=> Bugfix - Fixing agent state bug

plugins/acp/acp_plugin_gamesdk/interface.py
- remove duplicated `lastUpdated` (looks ok in node)
- add `providerName ` (already in node)
=> Fixes to AcpJob

plugins/acp/acp_plugin_gamesdk/acp_plugin.py, plugins/acp/examples/agentic/test_buyer.py, plugins/acp/examples/reactive/test_buyer.py
revert to old version of twitter plugin (0.2.2 / 0.2.3) which is the version used in ACP plugin
=> [acp plugin] fix: revert to old version of GAME twitter plugin

plugins/acp/acp_plugin_gamesdk/acp_client.py, plugins/acp/acp_plugin_gamesdk/acp_plugin.py, plugins/acp/acp_plugin_gamesdk/interface.py
To only tag seller in the first tweet of the track and improve coding conventions.
Tested locally and verified https://x.com/demo_meme_agent/status/1924749037452075423.
=> [ACP Plugin] Improve Tweet Content

plugins/acp/README.md, plugins/acp/acp_plugin_gamesdk/acp_client.py, plugins/acp/acp_plugin_gamesdk/acp_plugin.py, plugins/acp/acp_plugin_gamesdk/acp_token.py, plugins/acp/acp_plugin_gamesdk/configs.py, plugins/acp/examples/agentic/buyer.py, plugins/acp/examples/agentic/seller.py, plugins/acp/examples/reactive/buyer.py, plugins/acp/examples/reactive/seller.py
Added configs for test and mainet
=> Configs for test and mainet
