- src/game_sdk/game/README.md
Corrected `wayto` to `way to`
Corrected `exectue` to `execute`
> Improve Grammar in Docs

- .github/pr-labeler-config.yml
- .github/workflows/pr-labeler.yml
Add auto PR labeler according to current use cases.
- GitHub Action Extension:
[srvaroa/labeler](https://github.com/srvaroa/labeler): Label manager for PRs and Issues based on configurable conditions
- Auto apply labels to future PRs based on the following PR title conditions:
| Label | PR Title Regex |
| --- | --- |
| bugfix | (?i)fix\|bug |
| documentation | (?i)docs\|documentation |
| enhancement | (?i)feat\|feature\|enhance\|improve |
| plugin | (?i)plugin |
| test | (?i)test |
Can be tested over the private [test repo](https://github.com/game-by-virtuals/test-repo/compare/Ang-dot-patch-13?expand=1&title=plugin&template=default.md).
[Video Recording](https://drive.google.com/file/d/1GwQ7sM7TKRJc_45feICFpL9LbKfcV7zT/view?usp=sharing)
> [CI] Add Auto PR Labeler

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/default.md
- .github/PULL_REQUEST_TEMPLATE/plugin.md
- plugins/plugin_metadata_template.yml
Add PR templates for repo contributors to standardize PR documentation.
- Current repo PRs are lack of standardization
- Introducing PR templates to standardize PR documentation for proper PR context
- Introduces PR template for default change/plugin contribution
Can be tested over the private [test repo](https://github.com/game-by-virtuals/test-repo/compare/Ang-dot-patch-13?expand=1).
[Video Recording](https://drive.google.com/file/d/1pAuek53SZrsiMFq_e1M8ZnyUSiXW8ncQ/view?usp=sharing)
> [Chore] Add PR Templates

- plugins/telegram/README.md
- plugins/telegram/examples/test_telegram.py
- plugins/telegram/examples/test_telegram_game_functions.py
- plugins/telegram/plugin_metadata.yml
- plugins/telegram/pyproject.toml
- plugins/telegram/telegram_plugin_gamesdk/telegram_plugin.py
Add Telegram plugin for GAME Python SDK.
- GAME Node SDK PR for Telegram Plugin: [added telegram & discord client](https://github.com/game-by-virtuals/game-node/pull/12)
- README Validation
- Metadata Validation
Screen recording with `example/test_telegram.py`'s execution.
- Recordings
| Function | Video |
| --- | --- |
| Reply Message  | https://drive.google.com/file/d/1Dw-HbLBAB8d6t2XsET2RmXSaHRmbi8OM/view?usp=sharing |
| Send Media | https://drive.google.com/file/d/1AbxZHfwj5EgQxI435SlDznfPkGYY_E13/view?usp=drive_link |
| Creating Poll | https://drive.google.com/file/d/1XYQFvXibZR4Dmx1MDrnJgCUBCfL0On8U/view?usp=drive_link |
| Pin & Unpin Message | https://drive.google.com/file/d/1Z0b9cmbb9XC60l7RNONfNSL2APmI_K3P/view?usp=drive_link |
| Delete Message | …
> [Plugin] Add Telegram Plugin

- plugins/telegram/examples/test_telegram_game_functions.py
Clean up the clutter in `plugins/telegram/examples/test_telegram_game_functions.py`.
- Just cleaning up the clutter and add new lines where necessary according to coding practices.
- Initial PR: #97
> [Chore] Clean Up Telegram Plugin

- .github/PULL_REQUEST_TEMPLATE/plugin.md
- .github/workflows/pr-labeler.yml
- .github/workflows/validate-new-plugin-metadata.yml
- plugins/plugin_metadata_template.yml
Trigger automated CI validation for new plugin's metadata.
- [Notion](https://www.notion.so/virtualsprotocol/Proper-metadata-on-plugins-19e2d2a429e98092a92fc650708d065a?pvs=4)
- Added extra checkboxes for [`.github/PULL_REQUEST_TEMPLATE/plugin.md`](https://github.com/game-by-virtuals/game-python/blob/ci/yang-validate-plugin-metadata/.github/PULL_REQUEST_TEMPLATE/plugin.md)
- Added GH workflow to automate check for `plugin_metadata.yml`, will only trigger for new plugins folder, this check shall not affect existing plugin folders.
| Description | PR |
| --- | --- |
| [Part 1] [Chore] Add PR Templates | #80 |
| [Part 2] [CI] Add Validation to New Plugin's Metadata | ⬅️ |
Tested with #92 Mock PR.
- Screenshots
| Use Case | Screenshot | Result |
| --- | --- | --- |
| [Changes to existing …
> [CI] Add Validation to New Plugin's Metadata

- CONTRIBUTION_GUIDE.md
Update [`CONTRIBUTION_GUIDE.md`](https://github.com/game-by-virtuals/game-python/blob/main/CONTRIBUTION_GUIDE.md) according to latest CI & PR template updates.
Included docs related to
- `plugin_metadata.yml` requirement for new plugins.
- PR templates for either default/plugin contribution.
| Description | PR |
| --- | --- |
| [Part 1] [Chore] Add PR Templates | #80 |
| [Part 2] [CI] Add Validation to New Plugin's Metadata | #93 |
| [Part 3] [Docs] Update Contribution Guide | ⬅️ |
> [Docs] Update Contribution Guide

- plugins/twitter/twitter_plugin_gamesdk/game_twitter_auth.py
Enhance `game-twitter-plugin` server auth shutdown mechanism.
- move `self.server.shutdown()` to another thread to avoid server hang.
- standardize log output with GAME Node SDK.
- Video Recordings
| Use Case | Before | After |
| --- | --- | --- |
| Successful Auth | https://drive.google.com/file/d/16dj9SuviEH5MsP95Z7aJcIV5a_jnw5vs/view?usp=drive_link<br>Authenticated but **server hangs** (page loads indefinitely, terminal not ended) |  https://drive.google.com/file/d/1l9th6_hwZ6O2Os7KJI3fmRtiSJ83A6m6/view?usp=drive_link<br>Authenticated and successful auth page loaded, server is shutdown after |
| Failed Auth| https://drive.google.com/file/d/11rgsRO15odVfhyHt_F_f3kfJowR6QJvX/view?usp=drive_link<br>Invalid request page loaded but **terminal still active** (auth server still running) | …
> [Plugin] Enhance Game Twitter Plugin Auth Server Shutdown

- src/game_sdk/hosted_game/sdk.py
> fix: hosted GAME SDK endpoints expect strings from worldInfo

- plugins/acp/README.md
- plugins/acp/acp_plugin_gamesdk/acp_client.py
- plugins/acp/acp_plugin_gamesdk/acp_plugin.py
- plugins/acp/examples/test_seller.py
This casts job_id into an int at the first moment it is initialized. Getting rid of all the manual casting of job_ids to ints 
using int(job_id)
- None
- Makes code cleaner
- Nothing
- Nothing
- Code readability and maintainability 
- Does this have a dependent PR? Eg. link to original PR if this is a bug fix PR.
- No
Tested on test_buyer.py:
Output remains exactly the same
> Early casting of jobid or job_id to int

- plugins/acp/acp_plugin_gamesdk/acp_client.py
- plugins/acp/acp_plugin_gamesdk/interface.py
Fixes a bug that breaks browse_agents function
- None
- To fix a bug with browse_agent capabilities of ACP 
- Nothing
- Nothing
- It fixes a pretty breaking bug.
- No
Screenshot of bug:
Agent is unable to browse for other agents
Caused by:
Agents without any offerings
After bugfix:
Agent is able to browse for other agents
> Bugfix - Agents that have no offerings will trigger an error in the browse_agents function in AcpClient

- plugins/acp/acp_plugin_gamesdk/acp_client.py
- plugins/acp/acp_plugin_gamesdk/acp_token.py
Improves the logging for errors in acp_client.py
None
Better exception visibility
Nothing
Nothing
Logging and error handling
No
**Old error logging**
**New error logging**
> Refactor - Better Error Handling Logging

- plugins/acp/acp_plugin_gamesdk/acp_token.py
Fixes a bug whereby the _sign_transaction function was failing due to the evaluator address not being in the correct address format.
None
Fix bug breaking creation of jobs in ACP
Nothing
Nothing
Fixes a breaking bug
No
> Bugfix - Checksum Bug

- plugins/acp/acp_plugin_gamesdk/acp_plugin.py
Fixes errors when requireEvaluation returns as a string and not a boolean. GAME will not return anything other than strings even if we tell it to return something other than a string.
None
To cast requireEvaluation to a boolean instead of a string
Nothing
Nothing
Fixes a bug
> Bugfix - RequireEvaluation being a string and not a boolean

- plugins/acp/acp_plugin_gamesdk/acp_client.py
- Currently, when the agent perform a `search_agents`, the `search_agents` function may return the said agent in the result. 
- This may lead to the agent to commission a job from itself. 
- To prevent self-commission, we will exclude the agent in the search result
https://github.com/Virtual-Protocol/acp-be/pull/45
https://virtuals-protocol.atlassian.net/browse/ACP-162
https://github.com/game-by-virtuals/game-node/pull/117
To prevent agents from commissioning ownself for jobs.
> Make agent exclude itself from search agent result

- plugins/acp/acp_plugin_gamesdk/acp_client.py
- plugins/acp/acp_plugin_gamesdk/acp_plugin.py
- plugins/acp/acp_plugin_gamesdk/interface.py
Add job expiry option to `AcpPlugin` as introduced in [node version](https://github.com/game-by-virtuals/game-node/commit/127a9875c7bf73cf6a3306a124d9bcd7a13472cf).
- Add `job_expiry_duration_mins` to `AcpPluginOptions` as an optional integer value, defaulted to 1440 (24 hours).
- Add `expired_at` argument to `AcpClient`'s `create_job` function.
- Update timezone to `UTC` standard to avoid different job expiry across different timezone on job creation.
- Remove unused import `Dict` from `interface.py`.
Tested locally, agent able to create job according to `job_expiry_duration_mins` during `AcpPlugin` initialization.
eg:
```
acp_plugin = AcpPlugin(
options=AcpPluginOptions(
api_key=os.environ.get("GAME_DEV_API_KEY"),
acp_token_client=AcpToken(
os.environ.get("ACP_TOKEN"), …
```
> [ACP] Add Job Expiry Option

- plugins/acp/examples/agentic/README.md
- plugins/acp/examples/reactive/README.md
**Add documentation for `job_expiry_duration_mins` in ACP Python plugin setup**
- **Why this PR is needed?**  
To provide clarity on how job expiry works in the ACP plugin and prevent confusion around unresponsive job handling.
- **What does this add?**  
Adds a section in the README that explains the `job_expiry_duration_mins` parameter with use case context, code example, and rationale for its use.
- **What does this deprecate?**  
Nothing.
- **What does this improve?**  
Improves developer understanding of time-sensitive job coordination and encourages proper timeout configuration.
> [ACP] [Docs] Add Usage Guide for `job_expiry_duration_mins` in ACP Plugin Setup

- plugins/acp/acp_plugin_gamesdk/acp_plugin.py
- plugins/acp/examples/reactive/test_seller.py
Fixes the bug whereby you can't get jobId from inventory because inventory is a dict and not a list of IInventory objects.
Fixes a bug with dicts in self.produced_inventory
To fix a breaking bug
Nothing
Nothing
Stability of the plugin
No
> Bugfix - No Attribute jobid

- plugins/twitter/examples/.env.example
- plugins/twitter/examples/test_game_twitter.py
- plugins/twitter/examples/test_twitter.py
- plugins/twitter/twitter_plugin_gamesdk/game_twitter_plugin.py
- plugins/twitter/twitter_plugin_gamesdk/twitter_plugin.py
Adds an authentication gate during initialization of the `TwitterPlugin` & the `GameTwitterPlugin` to ensure valid credentials are provided before proceeding.
- Adds a logging setup in the `TwitterPlugin` & the `GameTwitterPlugin` to provide authentication-related logs.
- Introduces an authentication check during initialization by calling the `_check_authentication()` method, which validates the credentials and logs the authentication status.
Tested locally.
- Screenshots
| Plugin | Use Case | Before | After |
| --- | --- | --- | --- |
| `GameTwitterPlugin` | Empty `gameTwitterAccessToken` | <img alt="empty-gameTwitterAccessToken-before" src="https://github.com/user-attachments/assets/22702667-2800-4656-9907-a6b8578e9e95" /> | <img alt="empty-gameTwitterAccessToken-after" …
> [Twitter Plugin] Improve Error Log

- plugins/acp/acp_plugin_gamesdk/acp_plugin.py
The default get state function when a worker is created has 2 useless params in it.
> Bugfix - get state params 2

- plugins/acp/acp_plugin_gamesdk/acp_plugin.py
- plugins/acp/examples/agentic/test_buyer.py
- plugins/acp/examples/agentic/test_seller.py
- plugins/acp/examples/reactive/test_buyer.py
- plugins/acp/examples/reactive/test_seller.py
- src/game_sdk/game/agent.py
Reverting game-sdk get_state_fn back to 0.1.5 version behaviour
None
Fixes a discrepancy between
Nothing
Nothing
Stability of the system
https://github.com/game-by-virtuals/game-python/commit/ce2c3fce302a21af28ba09c3ede0f39bd474c09d#diff-9341d018d1ba05b7b68b612ad4566b86232b9349ff5d17988eb6a6d832d2c10d
> Bugfix - Better Param Naming

- plugins/acp/examples/agentic/buyer.py
- plugins/acp/examples/reactive/buyer.py
This pull request enhances the ACP plugin initialization by adding support for the cluster and graduated parameters. Specifically:
- `cluster="<your_agent_cluster>"` was added to target a specific job cluster.
- `graduated=True` was introduced to explicitly specify agent graduation status.
> [ACP] Add Cluster and Graduated Parameters to ACP Plugin Initialization

- plugins/acp/README.md
- plugins/acp/examples/reactive/README.md
> docs: update reduce agent state info in readme and update registry link

- plugins/acp/acp_plugin_gamesdk/acp_plugin.py
- plugins/acp/examples/agentic/buyer.py
- plugins/acp/examples/reactive/buyer.py
- plugins/acp/pyproject.toml
> refactor: Bump SDK Version and Add Graduation & Online Status Flags

- plugins/acp/acp_plugin_gamesdk/acp_plugin.py
- plugins/acp/acp_plugin_gamesdk/interface.py
- plugins/acp/examples/agentic/buyer.py
- plugins/acp/examples/reactive/buyer.py
- plugins/acp/examples/reactive/seller.py
- plugins/acp/pyproject.toml
and also improve agent prompts
tested and verified locally for
- agentic
- reactive
- job with requirement schema
- job without requirement schema
all works
> feat: improve acp sdk usage
